import type { PlaceDefaults } from "./stage-data";
import type { StageLanguage } from "./stage-language";

export type StageSourceParser =
  | "shv"
  | "jsonld"
  | "ics"
  | "loose"
  | "bhpa"
  | "pro-aero";

export type StageSourceDefinition = {
  id: string;
  name: string;
  organizerCountry: string;
  organizerType: "club" | "school" | "federation";
  url: string;
  parser: StageSourceParser;
  language: StageLanguage | null;
  active: boolean;
  defaults: PlaceDefaults;
};

export const internationalStageSources: StageSourceDefinition[] = [
  {
    id: "shv-training-travel",
    name: "FSVL · écoles suisses",
    organizerCountry: "Suisse",
    organizerType: "federation",
    url: "https://www.shv-fsvl.ch/einfach-finden/weiterbildung-flugreisen/",
    parser: "shv",
    language: null,
    active: true,
    defaults: {
      location: "Suisse",
      department: "Suisse",
      region: "Suisse",
      country: "Suisse",
    },
  },
  {
    id: "bhpa-qualified-pilot-courses",
    name: "BHPA · formations pilotes",
    organizerCountry: "Royaume-Uni",
    organizerType: "federation",
    url: "https://www.bhpa.co.uk/safety/courses/",
    parser: "bhpa",
    language: "en",
    active: true,
    defaults: {
      location: "Royaume-Uni",
      department: "Royaume-Uni",
      region: "Royaume-Uni",
      country: "Royaume-Uni",
    },
  },
  {
    id: "skyschool-uk-schedule",
    name: "SkySchool UK",
    organizerCountry: "Royaume-Uni",
    organizerType: "school",
    url: "https://www.skyschooluk.com/blogs/stories-from-the-sky/skyschool-s-2026-schedule",
    parser: "loose",
    language: "en",
    active: true,
    defaults: {
      location: "Royaume-Uni / Espagne",
      department: "Europe",
      region: "Europe",
      country: "Royaume-Uni",
    },
  },
  {
    id: "rise-paragliding-siv",
    name: "RISE Paragliding",
    organizerCountry: "Royaume-Uni",
    organizerType: "school",
    url: "https://www.riseparagliding.com/siv/",
    parser: "loose",
    language: "en",
    active: true,
    defaults: {
      location: "Ölüdeniz",
      department: "Muğla",
      region: "Riviera turque",
      country: "Turquie",
    },
  },
  {
    id: "siv-paragliding-ohrid",
    name: "SIV Paragliding Training",
    organizerCountry: "Macédoine du Nord",
    organizerType: "school",
    url: "https://www.siv-paragliding.com/dates-locations",
    parser: "loose",
    language: "en",
    active: true,
    defaults: {
      location: "Lake Ohrid · Galicica",
      department: "Ohrid",
      region: "Galicica",
      country: "Macédoine du Nord",
    },
  },
  {
    id: "flying-karlis-lake-garda",
    name: "Flying Karlis",
    organizerCountry: "Lettonie",
    organizerType: "school",
    url: "https://www.flyingkarlis.com/siv-course-lake-garda/",
    parser: "loose",
    language: "en",
    active: true,
    defaults: {
      location: "Lake Garda",
      department: "Lombardie",
      region: "Lombardie",
      country: "Italie",
    },
  },
  {
    id: "entrenuvols-siv",
    name: "Entrenúvols",
    organizerCountry: "Espagne",
    organizerType: "school",
    url: "https://entrenuvols.com/es/escuela-de-parapente/curso-siv/",
    parser: "jsonld",
    language: "es",
    active: true,
    defaults: {
      location: "Organyà",
      department: "Lleida",
      region: "Catalogne",
      country: "Espagne",
    },
  },
  {
    id: "fada-instructor-course",
    name: "FADA · Fédération aragonaise",
    organizerCountry: "Espagne",
    organizerType: "federation",
    url: "https://www.fada.aero/index_htm_files/CONVOCATORIA%20CURSO%202026.pdf",
    parser: "loose",
    language: "es",
    active: false,
    defaults: {
      location: "Castejón de Sos",
      department: "Huesca",
      region: "Aragon",
      country: "Espagne",
    },
  },
  {
    id: "prodelta-calendar",
    name: "Prodelta",
    organizerCountry: "Italie",
    organizerType: "school",
    url: "https://prodelta.it/archives/2856",
    parser: "loose",
    language: "it",
    active: true,
    defaults: {
      location: "Poggio Bustone",
      department: "Rieti",
      region: "Latium",
      country: "Italie",
    },
  },
  {
    id: "manta-paragliding-course",
    name: "Manta Paragliding School",
    organizerCountry: "Italie",
    organizerType: "school",
    url: "https://mantaonline.it/it/last-minute-updates/corso-parapendio-autunno-2026/",
    parser: "loose",
    language: "it",
    active: true,
    defaults: {
      location: "Borso del Grappa",
      department: "Trévise",
      region: "Vénétie",
      country: "Italie",
    },
  },
  {
    id: "shv-pro-aero-italian",
    name: "FSVL · Pink Baron",
    organizerCountry: "Suisse",
    organizerType: "federation",
    url: "https://www.shv-fsvl.ch/it/formazione/da-pedone-a-pilota/corso-pro-aero-2026/",
    parser: "pro-aero",
    language: "it",
    active: true,
    defaults: {
      location: "Capolago",
      department: "Tessin",
      region: "Tessin",
      country: "Suisse",
    },
  },
  {
    id: "flugschule-achensee-safety",
    name: "Flugschule Achensee",
    organizerCountry: "Autriche",
    organizerType: "school",
    url: "https://www.flugschule-achensee.at/de/mtermin/sicherheitstraining_idrosee",
    parser: "jsonld",
    language: "de",
    active: true,
    defaults: {
      location: "Lac d’Idro",
      department: "Lombardie",
      region: "Lombardie",
      country: "Italie",
    },
  },
  {
    id: "paragliding-academy-calendar",
    name: "Paragliding Academy",
    organizerCountry: "Allemagne",
    organizerType: "school",
    url: "https://paragliding-academy.com/termine/",
    parser: "jsonld",
    language: "de",
    active: true,
    defaults: {
      location: "Allgäu · sites annoncés",
      department: "Bavière",
      region: "Allgäu",
      country: "Allemagne",
    },
  },
  {
    id: "bregenzerwald-calendar",
    name: "Flugschule Bregenzerwald",
    organizerCountry: "Autriche",
    organizerType: "school",
    url: "https://www.gleitschirmschule.at/infos/termine/",
    parser: "loose",
    language: "de",
    active: true,
    defaults: {
      location: "Bezau · Bregenzerwald",
      department: "Vorarlberg",
      region: "Bregenzerwald",
      country: "Autriche",
    },
  },
  {
    id: "paragliding-austria-calendar",
    name: "Paragliding Austria · Time Flies",
    organizerCountry: "Autriche",
    organizerType: "school",
    url: "https://paragliding-austria.com/termine/",
    parser: "loose",
    language: "de",
    active: true,
    defaults: {
      location: "Kirchbach",
      department: "Carinthie",
      region: "Carinthie",
      country: "Autriche",
    },
  },
  {
    id: "pappus-calendar",
    name: "Gleitschirmschule Pappus",
    organizerCountry: "Allemagne",
    organizerType: "school",
    url: "https://www.gleitschirmschule-pappus.de/flugschule_termine.htm",
    parser: "loose",
    language: "de",
    active: true,
    defaults: {
      location: "Vosges",
      department: "Grand Est",
      region: "Grand Est",
      country: "France",
    },
  },
  {
    id: "flugschule-steiermark-calendar",
    name: "Flugschule Steiermark",
    organizerCountry: "Autriche",
    organizerType: "school",
    url: "https://www.flugschule-steiermark.at/kurse/",
    parser: "jsonld",
    language: "de",
    active: true,
    defaults: {
      location: "Styrie",
      department: "Styrie",
      region: "Styrie",
      country: "Autriche",
    },
  },
  {
    id: "flugschule-salzburg-training",
    name: "Flugschule Salzburg",
    organizerCountry: "Autriche",
    organizerType: "school",
    url: "https://www.flugschule-salzburg.com/termine-anmeldung-fortbildung/",
    parser: "loose",
    language: "de",
    active: true,
    defaults: {
      location: "Salzbourg",
      department: "Salzbourg",
      region: "Salzbourg",
      country: "Autriche",
    },
  },
  {
    id: "aufwind-austria-calendar",
    name: "Flugschule Aufwind",
    organizerCountry: "Autriche",
    organizerType: "school",
    url: "https://www.aufwind.at/de/termine/",
    parser: "jsonld",
    language: "de",
    active: true,
    defaults: {
      location: "Styrie",
      department: "Styrie",
      region: "Styrie",
      country: "Autriche",
    },
  },
  {
    id: "sky-club-austria-safety",
    name: "Sky Club Austria",
    organizerCountry: "Autriche",
    organizerType: "school",
    url: "https://www.skyclub-austria.at/de/skyclub/Trainingscenter/Sicherheitstraining.php",
    parser: "loose",
    language: "de",
    active: true,
    defaults: {
      location: "Hallstättersee",
      department: "Haute-Autriche",
      region: "Salzkammergut",
      country: "Autriche",
    },
  },
  {
    id: "dhv-courses",
    name: "DHV · formations",
    organizerCountry: "Allemagne",
    organizerType: "federation",
    url: "https://service.dhv.de/db2/",
    parser: "loose",
    language: "de",
    active: true,
    defaults: {
      location: "Allemagne",
      department: "Allemagne",
      region: "Allemagne",
      country: "Allemagne",
    },
  },
  {
    id: "fbvl-calendar",
    name: "FBVL · Fédération belge",
    organizerCountry: "Belgique",
    organizerType: "federation",
    url: "https://fbvl.be/",
    parser: "jsonld",
    language: "fr",
    active: true,
    defaults: {
      location: "Belgique",
      department: "Belgique",
      region: "Belgique",
      country: "Belgique",
    },
  },
];
